UPDATE question_dto set alternativa_correta =  4  WHERE ano = 2022 AND alternativa_correta is null AND azul = 1 AND linguagem = 1	
UPDATE question_dto set alternativa_correta =  5  WHERE ano = 2022 AND alternativa_correta is null AND azul = 1 AND linguagem = 2	

UPDATE question_dto set alternativa_correta =  3  WHERE ano = 2022 AND alternativa_correta is null AND azul = 2 AND linguagem = 1	
UPDATE question_dto set alternativa_correta =  4  WHERE ano = 2022 AND alternativa_correta is null AND azul = 2 AND linguagem = 2	

UPDATE question_dto set alternativa_correta =  2  WHERE ano = 2022 AND alternativa_correta is null AND azul = 3 AND linguagem = 1	
UPDATE question_dto set alternativa_correta =  3  WHERE ano = 2022 AND alternativa_correta is null AND azul = 3 AND linguagem = 2	

UPDATE question_dto set alternativa_correta =  4  WHERE ano = 2022 AND alternativa_correta is null AND azul = 4 AND linguagem = 1	
UPDATE question_dto set alternativa_correta =  1  WHERE ano = 2022 AND alternativa_correta is null AND azul = 4 AND linguagem = 2	

UPDATE question_dto set alternativa_correta =  5  WHERE ano = 2022 AND alternativa_correta is null AND azul = 5 AND linguagem = 1	
UPDATE question_dto set alternativa_correta =  1  WHERE ano = 2022 AND alternativa_correta is null AND azul = 5 AND linguagem = 2	

UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 6
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 7
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 8
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 9
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 10
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 11
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 12
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 13
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 14
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 15
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 16
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 17
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 18
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 19
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 20
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 21
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 22
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 23
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 24
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 25
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 26
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 27
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 28
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 29
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 30
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 31
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 32
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 33
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 34
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 35
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 36
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 37
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 38
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 39
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 40
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 41
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 42
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 43
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 44
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 45
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 46
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 47
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 48
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 49
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 50
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 51
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 52
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 53
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 54
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 55
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 56
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 57
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 58
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 59
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 60
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 61
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 62
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 63
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 64
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 65
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 66
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 67
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 68
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 69
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 70
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 71
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 72
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 73
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 74
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 75
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 76
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 77
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 78
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 79
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 80
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 81
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 82
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 83
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 84
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 85
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 86
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 87
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 88
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 89
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 90
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 91
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 92
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 93
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 94
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 95
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 96
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 97
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 98
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 99
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 100
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 101
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 102
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 103
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 104
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 105
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 106
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 107
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 108
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 109
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 110
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 111
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 112
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 113
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 114
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 115
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 116
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 117
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 118
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 119
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 120
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 121
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 122
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 123
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 124
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 125
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 126
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 127
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 128
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 129
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 130
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 131
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 132
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 133
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 134
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 135
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 136
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 137
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 138
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 139
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 140
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 141
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 142
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 143
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 144
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 145
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 146
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 147
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 148
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 149
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 150
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 151
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 152
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 153
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 154
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 155
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 156
UPDATE question_dto set alternativa_correta =  0 WHERE ano = 2022 AND alternativa_correta is null AND azul = 157
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 158
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 159
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 160
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 161
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 162
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 163
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 164
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 165
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 166
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 167
UPDATE question_dto set alternativa_correta =  3 WHERE ano = 2022 AND alternativa_correta is null AND azul = 168
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 169
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 170
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 171
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 172
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 173
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 174
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 175
UPDATE question_dto set alternativa_correta =  4 WHERE ano = 2022 AND alternativa_correta is null AND azul = 176
UPDATE question_dto set alternativa_correta =  1 WHERE ano = 2022 AND alternativa_correta is null AND azul = 177
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 178
UPDATE question_dto set alternativa_correta =  2 WHERE ano = 2022 AND alternativa_correta is null AND azul = 179
UPDATE question_dto set alternativa_correta =  5 WHERE ano = 2022 AND alternativa_correta is null AND azul = 180