UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 1 AND linguagem = 1
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 1 AND linguagem = 2
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2  WHERE ano = 2023 AND azul = 2 AND linguagem = 1
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 2 AND linguagem = 2
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4  WHERE ano = 2023 AND azul = 3 AND linguagem = 1
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 3 AND linguagem = 2
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1  WHERE ano = 2023 AND azul = 4 AND linguagem = 1
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 4 AND linguagem = 2
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2  WHERE ano = 2023 AND azul = 5 AND linguagem = 1
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 5 AND linguagem = 2


UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 6
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 7
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 8
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 9
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 10
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 11
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 12
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 13
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 14
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 15
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 16
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 17
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 18
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 19
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 20
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 21
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 22
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 23
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 24
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 25
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 26
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 27
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 28
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 29
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 30
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 31
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 32
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 33
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 34
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 35
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 36
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 37
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 38
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 39
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 40
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 41
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 42
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 43
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 44
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 45
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 46
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 47
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 48
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 49
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 50
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 51
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 52
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 53
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 54
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 55
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 56
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 57
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 58
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 59
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 60
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 61
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 62
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 63
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 64
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 65
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 66
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 67
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 68
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 69
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 70
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 71
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 72
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 73
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 74
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 75
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 76
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 77
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 78
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 79
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 80
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 81
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 82
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 83
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 84
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 85
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 86
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 87
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 88
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 89
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 90
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 91
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 92
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 93
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 94
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 95
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 96
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 97
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 98
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 99
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 100
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 101
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 102
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 103
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 104
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 105
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 106
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 107
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 108
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 109
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 110
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 111
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 112
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 113
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 114
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 115
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 116
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 117
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 118
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 119
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 120
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 121
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 122
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 123
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 124
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 125
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 126
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 127
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 128
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 129
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 130
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 131
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 132
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 133
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 134
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 135
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 136
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 137
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 138
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 139
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 140
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 141
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 142
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 143
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 144
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 145
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 146
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 147
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 148
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 149
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 150
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 151
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 152
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 153
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 154
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 155
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 156
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 157
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 158
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 159
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 160
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 161
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 162
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 163
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 0 WHERE ano = 2023 AND azul = 164
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 165
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 166
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 167
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 168
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 169
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 4 WHERE ano = 2023 AND azul = 170
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 171
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 172
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 173
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 174
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 175
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 5 WHERE ano = 2023 AND azul = 176
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 1 WHERE ano = 2023 AND azul = 177
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 2 WHERE ano = 2023 AND azul = 178
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 179
UPDATE [ENEM_SIMULADO].[dbo].[question_dto] SET [alternativa_correta] = 3 WHERE ano = 2023 AND azul = 180